<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AndroidManager.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DiscUtils.Core" Version="0.16.13" />
    <PackageReference Include="DiscUtils.Ext" Version="0.16.13" />
    <PackageReference Include="SharpCompress" Version="0.50.4" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AndroidManager.Security" />
    <InternalsVisibleTo Include="AndroidManager.Security.Tests" />
    <InternalsVisibleTo Include="AndroidManager.Device.Tests" />
  </ItemGroup>

</Project>
