# One-click Companion APK build -> dist/apk/
param(
    [ValidateSet("Debug", "Release")]
    [string]$Configuration = "Release",
    [switch]$Install
)

$ErrorActionPreference = "Stop"
$root = if ((Split-Path $PSScriptRoot -Leaf) -eq "scripts") {
    Split-Path $PSScriptRoot -Parent
} else {
    $PSScriptRoot
}

$companion = Join-Path $root "AndroidCompanion"
$outApkDir = Join-Path $root "dist\apk"
$wrapperJar = Join-Path $companion "gradle\wrapper\gradle-wrapper.jar"

Write-Host ""
Write-Host "=== SeND ANDROID MANAGER - Companion APK ===" -ForegroundColor Cyan
Write-Host "Config: $Configuration"
Write-Host ""

if (-not (Test-Path $companion)) {
    throw "AndroidCompanion folder missing: $companion"
}

function Resolve-JavaHome {
    $candidates = [System.Collections.Generic.List[string]]::new()
    if ($env:JAVA_HOME) { [void]$candidates.Add($env:JAVA_HOME) }
    [void]$candidates.Add("C:\Program Files\Android\Android Studio\jbr")
    [void]$candidates.Add((Join-Path $env:LOCALAPPDATA "Programs\Android Studio\jbr"))
    [void]$candidates.Add("C:\Program Files\Zulu\zulu-21")

    foreach ($c in $candidates) {
        if (-not $c) { continue }
        $java = Join-Path $c "bin\java.exe"
        if (Test-Path $java) { return $c }
    }

    $jdk17 = Get-Item "C:\Program Files\Microsoft\jdk-17*" -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($jdk17 -and (Test-Path (Join-Path $jdk17.FullName "bin\java.exe"))) {
        return $jdk17.FullName
    }

    $where = Get-Command java -ErrorAction SilentlyContinue
    if ($where) {
        return (Split-Path (Split-Path $where.Source -Parent) -Parent)
    }
    return $null
}

$javaHome = Resolve-JavaHome
if (-not $javaHome) {
    throw "Java not found. Install Android Studio JBR or JDK 17+."
}
$env:JAVA_HOME = $javaHome
Write-Host "JAVA_HOME: $javaHome" -ForegroundColor DarkGray

function Resolve-AndroidSdk {
    $candidates = [System.Collections.Generic.List[string]]::new()
    if ($env:ANDROID_HOME) { [void]$candidates.Add($env:ANDROID_HOME) }
    if ($env:ANDROID_SDK_ROOT) { [void]$candidates.Add($env:ANDROID_SDK_ROOT) }
    [void]$candidates.Add((Join-Path $env:LOCALAPPDATA "Android\Sdk"))
    [void]$candidates.Add((Join-Path $env:USERPROFILE "AppData\Local\Android\Sdk"))

    foreach ($c in $candidates) {
        if ($c -and (Test-Path (Join-Path $c "platform-tools"))) { return $c }
    }
    return $null
}

$sdk = Resolve-AndroidSdk
if (-not $sdk) {
    throw "Android SDK not found. Install Android Studio SDK (platform-tools)."
}
$env:ANDROID_HOME = $sdk
$env:ANDROID_SDK_ROOT = $sdk
Write-Host "ANDROID_SDK: $sdk" -ForegroundColor DarkGray

$sdkPathEscaped = $sdk.Replace("\", "\\")
$localProps = Join-Path $companion "local.properties"
@"
## Generated by scripts/Build-Apk.ps1 - do not commit
sdk.dir=$sdkPathEscaped
"@ | Set-Content -Path $localProps -Encoding ASCII

if (-not (Test-Path $wrapperJar)) {
    Write-Host "Downloading gradle-wrapper.jar..." -ForegroundColor Yellow
    $wrapperDir = Split-Path $wrapperJar -Parent
    New-Item -ItemType Directory -Force -Path $wrapperDir | Out-Null
    $urls = @(
        "https://github.com/gradle/gradle/raw/v8.2.1/gradle/wrapper/gradle-wrapper.jar",
        "https://raw.githubusercontent.com/gradle/gradle/v8.2.1/gradle/wrapper/gradle-wrapper.jar"
    )
    $ok = $false
    foreach ($url in $urls) {
        try {
            Invoke-WebRequest -Uri $url -OutFile $wrapperJar -UseBasicParsing
            if ((Get-Item $wrapperJar).Length -gt 10000) { $ok = $true; break }
        } catch {
            Write-Host "  retry: $url" -ForegroundColor DarkYellow
        }
    }
    if (-not $ok) {
        throw "Could not download gradle-wrapper.jar (check internet)."
    }
}

$task = if ($Configuration -eq "Release") { ":app:assembleRelease" } else { ":app:assembleDebug" }

Write-Host "Gradle: $task" -ForegroundColor Yellow
Push-Location $companion
try {
    & .\gradlew.bat $task --no-daemon
    if ($LASTEXITCODE -ne 0) { throw "Gradle build failed ($LASTEXITCODE)" }
}
finally {
    Pop-Location
}

$built = if ($Configuration -eq "Release") {
    Join-Path $companion "app\build\outputs\apk\release\app-release-unsigned.apk"
} else {
    Join-Path $companion "app\build\outputs\apk\debug\app-debug.apk"
}

if (-not (Test-Path $built) -and $Configuration -eq "Release") {
    $alt = Join-Path $companion "app\build\outputs\apk\release\app-release.apk"
    if (Test-Path $alt) { $built = $alt }
}

if (-not (Test-Path $built)) {
    throw "APK not found: $built"
}

$apkSize = (Get-Item $built).Length
Write-Host "Built APK: $built ($([math]::Round($apkSize/1MB, 2)) MB)" -ForegroundColor Green

New-Item -ItemType Directory -Force -Path $outApkDir | Out-Null
$destName = if ($Configuration -eq "Release") { "AndroidManagerCompanion-release.apk" } else { "app-debug.apk" }
$dest = Join-Path $outApkDir $destName
$alias = Join-Path $outApkDir "AndroidManagerCompanion.apk"

function Get-DriveFreeBytes([string]$path) {
    try {
        $full = $path
        if (Test-Path $path) {
            $full = (Resolve-Path $path).Path
        }
        $root = [System.IO.Path]::GetPathRoot($full)
        if ([string]::IsNullOrWhiteSpace($root)) { return $null }
        $letter = $root.Substring(0, 1)
        $drive = Get-PSDrive -Name $letter -ErrorAction SilentlyContinue
        if ($drive) { return [int64]$drive.Free }
    } catch { }
    return $null
}

$free = Get-DriveFreeBytes $outApkDir
# Need room for one APK copy (+ small margin). Alias is a second name from the same file when possible.
$need = $apkSize + 2MB
if ($null -ne $free -and $free -lt $need) {
    $freeMb = [math]::Round($free / 1MB, 1)
    $needMb = [math]::Round($need / 1MB, 1)
    Write-Host ""
    Write-Host "DISK FULL: destination drive has $freeMb MB free; need ~$needMb MB." -ForegroundColor Red
    Write-Host "Gradle already built the APK - use it directly:" -ForegroundColor Yellow
    Write-Host "  $built" -ForegroundColor Cyan
    Write-Host 'Free space (Temp, Downloads, old dist\apk, Gradle caches) then re-run, or:' -ForegroundColor Yellow
    Write-Host "  adb install -r `"$built`"" -ForegroundColor Cyan
    throw 'Not enough disk space to copy APK into dist\apk'
}

try {
    # Single copy into dist, then hardlink/alias to avoid doubling disk use.
    Copy-Item $built $dest -Force
    if (Test-Path $alias) { Remove-Item $alias -Force -ErrorAction SilentlyContinue }
    try {
        New-Item -ItemType HardLink -Path $alias -Target $dest -Force | Out-Null
    } catch {
        # Hardlink may fail across volumes or on some FS — fall back to one more copy if space allows.
        $free2 = Get-DriveFreeBytes $outApkDir
        if ($null -eq $free2 -or $free2 -ge ($apkSize + 1MB)) {
            Copy-Item $dest $alias -Force
        } else {
            Write-Host "Skipped second APK name (disk low). Primary: $dest" -ForegroundColor DarkYellow
            $alias = $dest
        }
    }
}
catch [System.IO.IOException] {
    Write-Host ""
    Write-Host "Copy to dist\apk failed: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host "APK is still available here:" -ForegroundColor Yellow
    Write-Host "  $built" -ForegroundColor Cyan
    throw
}

Write-Host ""
Write-Host "APK: $dest" -ForegroundColor Green
if ($alias -ne $dest) {
    Write-Host "Also: $alias" -ForegroundColor Green
}

if ($Install) {
    $adb = Join-Path $sdk "platform-tools\adb.exe"
    if (-not (Test-Path $adb)) { $adb = "adb" }
    Write-Host "adb install -r ..." -ForegroundColor Yellow
    & $adb install -r $dest
    if ($LASTEXITCODE -ne 0) {
        Write-Host "adb install failed (is a device connected?)." -ForegroundColor DarkYellow
    }
}

Write-Host "APK build OK." -ForegroundColor Green
